config/routes.rb
Codeforgood::Application.routes.draw do
  devise_for :companies
  resources :companies do 
    resources :updates do
      member {post :change_privacy}
    end
  end

  root 'main#index'
  get '(test)/'=>'main#test'
  get '(index)/' => 'main#index'
  get 'contact' => 'main#contact', as: 'contact'
  post 'mail/sendmail' => 'mail#sendmail', as: 'sendmail'

end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :updates, :dependent => :destroy

  validates_presence_of :name
end

app/models/update.rb
class Update < ActiveRecord::Base
	belongs_to :company
	validates_numericality_of :impact, :employed, :volunteers, :raised_funds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def devise_parameter_sanitizer
    if resource_class == Company
      Company::ParameterSanitizer.new(Company, :company, params)
    else
      super # Use the default one
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :authenticate_company!
	def create

	end

	def show
		@company = Company.find(params[:id])
		@updates = @company.updates.all
	end

	def index
		@companies = Company.where(admin:false)
	end

	# def update

	# end
end

app/controllers/mail_controller.rb
class MailController < ApplicationController
	def sendmail
		if params[:email]=="" || params[:subject]=="" || params[:message]==""
			flash[:error] = "Please fill all the fields !"
			redirect_to :back
		else
			email = params[:email]
			subject = params[:subject]
			message = "You have one email from #{email} \n \n" + params[:message]
			CompanyMailer.contact(email, subject, message).deliver

			return if request.xhr?
				redirect_to :root

		end
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index 
		@companies = Company.where(admin: false)
	end

	def test
	end

	def contact
	end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
	def create
		@company = Company.find(params[:company_id])
		@update = Update.new(params[:update].permit(:update_SEI, :challenge, :support_req,
													:impact, :employed, :volunteers, :raised_funds))
		@message = "Hello, #{@company.name}\n has uploaded new information."
		@subject = "Updates from #{@company.name}"
		@email = Company.where(admin: true).email.take

		@update.company_id = @company.id
		if @update.save
			redirect_to @company
			CompanyMailer.contact(@email,@subject,@message).deliver
		else
			render "new"
		end
	end

	def index
		@updates = Update.all()
	end

	def update
		@company = Company.find(params[:company_id])
		@update = Update.find(params[:id])

		if @update.update(params[:update].permit(:update_SEI, :challenge, :support_req,
													:impact, :employed, :volunteers, :raised_funds))
			redirect_to @company
		else
			render "edit"
		end
	end

	def edit
		@company = Company.find(params[:company_id])
		@update = Update.find(params[:id])
	end

	def show
		@update = Update.find(params[:id])
	end

	def new
		@company = Company.find(params[:company_id])
		@update = Update.new
	end

	def destroy
		@update = Update.find(params[:id])
		@update.destroy
		redirect_to updates_path
	end

	def change_privacy
		@update = Update.find(params[:id])
		@update.privacy = !@update.privacy
		if @update.save
			redirect_to :back
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/companies/formupdate.html.erb
<%= form_tag(:controller => "companies", :action => "create") do %>
  <%= label_tag(:update_SEI, "SEI Updates") %><br />  
  <%= text_area_tag(:update_SEI, :size => "44x6") %><br />

  <%= submit_tag("Update") %>  
<% end %>

app/views/companies/index.html.erb
<div class="container-fluid">
	<div class="tabbable">
		<div class="row-fluid">
			<div class="span2">
		  		<div class="tabbable tabs-left">
	  				<ul class="nav nav-tabs">
	  					
						<% @companies.each do |company| %>
							<li><a href="#pane<%=company.id%>" data-toggle="tab"><%=company.name%></a></li>
						<% end %>
		  			</ul>
		  		</div>
			</div>
			<div class="span8">
			  	<div class="tab-content">
			  	<% @companies.each do |company| %>
			  		<%if company.id==1%>
				  		<div id="pane<%=company.id%>" class="tab-pane active">

				  			<h3><%=company.name%></h3>
				   		 	<pre>Description: <%= company.description%> ...</pre>
				   		 	<%= link_to "View report for "+company.name, company_path(company.id), class: "btn" %>
				   		</div>
					<%else%>
				  		<div id="pane<%=company.id%>" class="tab-pane">
				   			<h3><%=company.name%></h3>
				   		 	<pre>Description: <%= company.description%> ...</pre>
				   		 	<%= link_to "View report for "+company.name, company_path(company.id), class: "btn" %>

				   		</div>
					<%end%> 
				<%end%> 
			    </div> 
			</div><!-- /.tab-content -->
		</div>
	</div><!-- /.tabbable -->
</div><!-- /.tabbable -->

app/views/companies/show.html.erb
<style>
	.maindiv {
		padding-left:10%;
	}

	.noupdates{
		padding-bottom:1%;
	}

	.spacerighttop{
		padding-right: 5%;
		padding-top: 5%;
	}

	.cutright{
		margin-right:10%;
	}

	.green{
		color: #9ACD32;
	}

</style>

<div class="maindiv"><%#= @company.name %>

	<%if @company.updates.blank?%>
		<h4 class="noupdates">No updates at this time</h4>
	<%else%>
		<div class="row-fluid">
			<%= link_to "Add new update", new_company_update_path(@company) ,class: "btn btn-large btn-success"%>
			<%= link_to "Help!", contact_path ,class: "btn btn-large btn-danger"%>
		</div>		

		<%
		require 'gchart'
		impacted = []
		employees = []
		volunteers = []
		funds = []
		grid= []
		%>
	    
		<h3 style="display: none">People impacted</h3>
		<% @company.updates.reverse![0..11].each_with_index do |u, index| %>
			<% if !u.impact.blank? %>
				<p style="display: none"><%=impacted[index]=u.impact %></p>
			<% end %>

			<h3 style="display: none">Number of employees</h3>
			<% if !u.employed.blank? %>
				<p style="display: none"><%=employees[index]=u.employed %></p>
			<% end %>

			<h3 style="display: none">Number of volunteers</h3>
			<% if !u.volunteers.blank? %>
				<p style="display: none"><%=volunteers[index]= u.volunteers %></p>
			<% end %>

			<h3 style="display: none">Raised funds</h3>
			<% if !u.raised_funds.blank? %>
				<p style="display: none"><%=funds[index]= u.raised_funds %></p>
			<% end %>
		<% end %>
		<p style="display: none">
			<%=grid[0]=impacted.max%>
			<%=grid[1]=employees.max%>
			<%=grid[2]=volunteers.max%>
			<%=grid[3]=funds.max%>
		</p>	

		<div class="row-fluid">
			<img class="spacerighttop" src="<%=
		    	Gchart.line(:size => '500x300', 
		    				:data => [impacted], 
		    				:line_colors => 'EB3724',
		    				:title => "People impacted",
		    				:axis_with_labels => 'x,y',
            				:axis_labels => ['-1y|-9m|-6m|-3m|This month', [0,grid[0]]])%>">
			<img class="spacerighttop" src="<%=
		    	Gchart.line(:size => '500x300', 
		    				:data => [employees], 
		    				:line_colors => 'EB3724',
		    				:title => "Number of employees",
		    				:axis_with_labels => 'x,y',
            				:axis_labels => ['-1y|-9m|-6m|-3m|This month', [0,grid[1]]])%>">
		</div>
		<div class="row-fluid">
			<img class="spacerighttop" src="<%=
		    	Gchart.line(:size => '500x300', 
		    				:data => [volunteers], 
		    				:line_colors => 'EB3724',
		    				:title => "Number of volunteers",
		    				:axis_with_labels => 'x,y',
            				:axis_labels => ['-1y|-9m|-6m|-3m|This month', [0,grid[2]]])%>">
		    <img class="spacerighttop" src="<%=
		    	Gchart.line(:size => '500x300', 
		    				:data => [funds], 
		    				:line_colors => 'EB3724',
		    				:title => "Raised funds",
		    				:axis_with_labels => 'x,y',
            				:axis_labels => ['-1y|-9m|-6m|-3m|This month', [0,grid[3]]])%>">
		</div>
		
		<h3 class="green">Report Update</h3>
		<% @company.updates.reverse!.each do |u| %>
		<% if !current_company.admin? %>
			<%= link_to "Change privacy on report " +  u.created_at.to_s , change_privacy_company_update_path(@company, u), method: "post", class: "btn" %>
		<% end %>
			<!-- -->
		<% if !u.privacy || current_company.admin? %>
			<hr>
			<span class="green">Date:<%=u.created_at%><br></span>
				<% if !u.update_SEI.blank? %>
					<h5>Major SEI Updates</h5>
					<pre class="cutright"><%=u.update_SEI %></pre>
				<% end %>
				<% if !u.challenge.blank? %>
					<h5>Challenges faced</h5>
					<pre class="cutright"><%= u.challenge %></pre>
				<% end %>
					<% if !u.support_req.blank? %>
					<h5>Support required</h5>
					<pre class="cutright"><%= u.support_req %></pre>
				<% end %>
				<% if !u.impact.blank? %>
					<h5>People impacted</h5>
					<pre class="cutright"><%=u.impact%></pre>
				<% end %>
				<% if !u.employed.blank? %>
					<h5>Number of employees</h5>
					<pre class="cutright"><%= u.employed %></pre>
				<% end %>
					<% if !u.volunteers.blank? %>
					<h5>Number of volunteers</h5>
					<pre class="cutright"><%= u.volunteers %></pre>
				<% end %>
				<% if !u.raised_funds.blank? %>
					<h5>Raised funds</h5>
					<pre class="cutright"><%= u.raised_funds %></pre>
				<% end %>
			<% end %>
		<% end %> 
		
		
		
<%end%>

<div class="row-fluid">
<br><%= link_to "Add new update", new_company_update_path(@company) ,class: "btn btn-large btn-success"%>
	<%= link_to "Help!", contact_path ,class: "btn btn-large btn-danger"%>
</div>
<br>
<br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Code for Good</title>

    <!-- Custom styles for this template -->

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">

    .container-fluid {
    	width: 80%;
    	padding-left: 10%;
    	padding-right: 10%;
    	padding-top: 0%;
    }
    .header {
    	width: 80%;
    	padding-top: 2%;
    	padding-left: 10%;
    	padding-right: 10%;
    }
    .image {
    	text-align: left;
    	max-width: 280px;
    }
    .footer{
    	text-align: center;
    }

    #smallhr{
    	width:100%;
    	padding-left: 0%;
    }
    .btn{
      margin-top: 3%;
    }
      #wrap {
        min-height: 100%;
        height: auto !important;
        height: 100%;
        /* Negative indent footer by its height */
        margin: 0 auto -60px;
      }
      .mailA {
        box-shadow: 7px 7px 4px #D8D8D8;
        border: 5px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
        margin-right: 15px;
        font-size: 19px;
        padding: 5px 5px 5px 5px;
        color: #9ACD32;
      }
      .fb-like {
        float: left;
        margin-left: 3%;
      }
      .allRights {
        float: right;
        margin-left: 3%;
        margin-right: 3%;
      }
      .twitter-share-button {
        float: left;
        margin-right: 3%;
      }
      .navbar-fixed-bottom {
        height: 4%;
        margin-top: 10px;
        margin-left: 10%;
        width: 80%;
        background-color: #FFFFFF;
      }
      .row-fluid {
        margin-right: 10%;
      }
      .alert .alert-block {
        width: 10%;
      }
    </style>

    

</head>
<body>

 <script type="text/javascript">
     $(function showAdvice() {
        var rand=Math.floor((Math.random(1999)*10)+1);
       if(rand%3 == 0) $("#textToBeChanged").text("Do you need legal advice? We can help!");
       if(rand%3 == 1) $("#textToBeChanged").text("Do you need financial advice? You can count on us!");
       if(rand%3 == 2) $("#textToBeChanged").text("Do you need support with Human Resources issues? We are here for you!");
     });
     </script>

	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="container-fluid" onload="showAdvice()">
  <div class="alert alert-success" onload="showAdvice()">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h2 class="text-center" id="textToBeChanged" >Bla bla</h2>
  </div>
</div>


	<div class="header text-left">
        <ul class="nav nav-pills pull-right">
        <% if company_signed_in? %>
                <div  class="mailA"><%= current_company.email %> </div>
                <%# link_to "My Account", companies_path(current_company.id) %>
                <%= link_to "Sign out", destroy_company_session_path, :method => :delete, class: "btn btn-large btn-error" %>
                
              <% else %>
                  <%= link_to "Login", new_company_session_path, class: "btn btn-large btn-success" %> 
                  <%= link_to "Sign up", new_company_registration_path, class: "btn btn-large btn-success", role: "button" %>
        <% end %>
        <%= link_to "Home", root_path,  class: "btn btn-large btn-success", role: "button" %>
        </ul>
       <a href="index.html"> <img class="image" src="http://socialentrepreneurs.ie/wp-content/themes/sei/images/logo.png"></a>

      <hr id="smallhr">
      </div>  

      <%= yield %>

	<div class="navbar-fixed-bottom">
    <div class="row-fluid">
        <div class="fb-like" data-href="https://www.facebook.com/socialentrepreneursireland" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
        <a href="http://www.linkedin.com/company/social-entrepreneurs-ireland "><img src="http://thelinkedinman.yourbusinesschannel.com/files/2012/01/linkedinbutton.jpg" style="height:100%;"/></a>
        
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://socialentrepreneurs.ie/" data-text="I'm lovin' it!" data-size="large">Tweet</a>
        <p class="allRights">&copy; Social Entrepreneurs 2013</p>
        
    </div>
    </div>
  

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

</body>
</html>

app/views/main/contact.html.erb
<style type="text/css">
  .form-signin {
        width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
        box-shadow: 7px 7px 4px #D8D8D8;
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: 35px;
        margin-top: 15px;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
      .other {
        padding-top: 5%;
      }

      .text-center {
        padding-bottom: 10%;
      }

      .sgnBtn {
        margin-left: 25%;
        margin-top: 35px;
      }

</style>
<div class="container-fluid">


<div class="form-signin">
<%= form_tag :action => 'sendmail', :controller => "mail"  %>
	<h1 class="text-center">Contact Us</h1>
	<%= label :subject, "Subject" %>
	<%= text_field_tag :subject, nil, class: "input-block-level", :placeholder => "Subject..." %>

	<% if current_company %>
		<%= hidden_field_tag "email", current_company.email %>
	<%else%>
		<%= label :email, "Please write you e-mail address" %>
		<%= email_field_tag :email, nil, class: "input-block-level", :placeholder => "Your e-mail address so we can contact you back..." %>	

	<%end%>

	<%= label :message, "Message" %>
	<%= text_area_tag :message,nil, class: "input-block-level", :placeholder => "Tell us something here..." %>
	
	<%= submit_tag "Send us an e-mail", class: "btn btn-success sgnBtn" %>	
</div>
</div>

app/views/main/index.html.erb
<style type="text/css">
/* CUSTOMIZE THE CAROUSEL
    -------------------------------------------------- */

    /* Carousel base class */
    .carousel {
      margin-bottom: 20px;
    }

    .carousel .container {
      position: relative;
      z-index: 9;
    }

    .carousel-control {
      height: 80px;
      margin-top: 0;
      font-size: 120px;
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
      background-color: transparent;
      border: 0;
      z-index: 10;
    }

    .carousel .item {
      height: 500px;
    }
    .carousel img {
      position: absolute;
      top: 0;
      left: 0;
      min-width: 100%;
      height: 500px;
    }

    .carousel-caption {
      background-color: transparent;
      position: static;
      max-width: 550px;
      padding: 0 20px;
      margin-top: 400px;
      padding-right: 150px;
    }
    .carousel-caption h1,
    .carousel-caption .lead {
      margin: 0;
      line-height: 1.25;
      color: #fff;
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
    }
    .carousel-caption .btn {
      margin-top: -10px;
    }
    .container-fluid {
    	padding: 0px 0px 0px 0px;
    	margin-left: 10%;
    	margin-right: 10%;
    }
    h2 {
    	margin-top: 0px;
    	color:#9ACD32;
    }
    .row {
    	padding: 0px 0px 0px 0px;
    	margin-left: 18%;
    	margin-right: 10%;
    	padding-bottom: 100px;
    }

</style>


<div class="container-fluid">
	<h2 class="text-center">Changing Ireland by significantly increasing the impact of Ireland’s leading social entrepreneurs.</h2>
	 <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="http://socialentrepreneurs.ie/assets/2012/10/Fumbally-Exchange.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h2 style="color:#FAFAFA"> View the <a href="./companies/" class="btn btn-success">companies</a> that we support.</h2>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://socialentrepreneurs.ie/assets/2012/09/WebTalk.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h2 style="color:#FAFAFA"> View the <a href="./companies/" class="btn btn-success">companies</a> that we support.</h2>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://socialentrepreneurs.ie/assets/2012/09/EM-Banner1.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h2 style="color:#FAFAFA"> View the <a href="./companies/" class="btn btn-success">companies</a> that we support.</h2>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->

    <!-- Marketing messaging and featurettes
    ================================================== -->



    <div class="container-marketing">
 		
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
          <img class="img-circle" data-src="holder.js/140x140">
          <h2>The Challenge</h2>
          <p>In order to solve some of Ireland’s social and environmental problems, we need innovative thinking and new solutions. We need to challenge the status quo and try new things. We need to focus on effectiveness and on impact.</p> <p>We are lucky to have people all over Ireland who are developing new solutions to our societal problems. Without support, however, these ideas can struggle to make enough of an impact. We know we can’t afford to wait for these solutions to grow and scale, as the problems we face are immediate and urgent.</p>
          
        </div><!-- /.span4 -->
        <div class="span4">
          <img class="img-circle" data-src="holder.js/140x140">
          <h2>The Idea</h2>
          <p>When a social entrepreneur comes up with a great new solution to social problems, we believe that they should get the funding and support that they need to scale and grow, so that they can impact as many people as possible, as quickly as possible.</p><p>At Social Entrepreneurs Ireland, we find the social entrepreneurs who have the most potential to have an impact, work with them intensively to develop their projects and ensure that their ideas are implemented as effectively and efficiently as possible. Our Awards Programmes provides up to €200,000 worth of support per social entrepreneur over the course of up to two years.</p>
          
        </div><!-- /.span4 -->
        <div class="span4">
          <img class="img-circle" data-src="holder.js/140x140">
          <h2>The Impact</h2>
          <p>Over the last 7 years we have supported 161 social entrepreneurs, investing €4.9 million in their projects, and providing significant additional supports. These in turn have directly impacted over 200,000 people across Ireland and created over 800 employment opportunities in the process.</p><p>We’ve seen ideas grow from ideas in a bedroom to national movements, people’s passion turned into impact and Ireland fundamentally changed in many ways.</p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->

</div>

app/views/main/test.html.erb
<%= form_tag do %>
  <%= label_tag(:my_name, "My name is:") %>
  <%= text_field_tag(:my_name) %>
  <%= submit_tag("Process") %>
<% end %>

app/views/updates/_form.html.erb
<%= form_for [@company, @update] do |f| %>
	<%= f.label :update_SEI, "Updates" %>
	<%= f.text_area :update_SEI, size: "12x3" %>
	
	<%= f.label :challenge, "Challenges" %>
	<%= f.text_area :challenge, size: "12x3" %>
	
	<%= f.label :support_req, "Support required" %>
	<%= f.text_area :support_req, size: "12x3" %>
	
	<%= f.label :impact, "People impacted" %>
	<%= f.text_field :impact %>
	
	<%= f.label :employed, "Number of employees" %>
	<%= f.text_field :employed %>

	<%= f.label :volunteers, "Number of volunteers" %>
	<%= f.text_field :volunteers %>

	<%= f.label :raised_funds, "Raised funds" %>
	<%= f.text_field :raised_funds %>

	<%= f.submit "Submit", class: "btn-large btn-primary" %>
<% end %>

app/views/updates/edit.html.erb
<%= render "form" %>

app/views/updates/new.html.erb
<style type="text/css">
      .text-center {
        padding-bottom: 10%;
      }

      .sgnBtn {
        margin-top: 35px;
      }

      .other {
      	margin-bottom: 15px;
      }

      .text {
      	font-size: 20px;
      	color: #9ACD32;
      }
</style>

<div class="container">
	<%= form_for [@company, @update] do |f| %>
		<div class="other"><%= f.label :update_SEI, "Updates", class: "text" %>
		<%= f.text_area :update_SEI, rows: "5", class: "input-xxlarge" %></div>
		
		<div class="other"><%= f.label :challenge, "Challenges", class: "text" %>
		<%= f.text_area :challenge, rows: "5", class: "input-xxlarge" %></div>
		
		<div class="other"><%= f.label :support_req, "Support required", class: "text" %>
		<%= f.text_area :support_req, rows: "5", class: "input-xxlarge" %></div>
		
		<div class="other"><%= f.label :impact, "People impacted", class: "text" %>
		<%= f.text_field :impact %></div>
		
		<div class="other"><%= f.label :employed, "Number of employees", class: "text" %>
		<%= f.text_field :employed %></div>

		<div class="other"><%= f.label :volunteers, "Number of volunteers", class: "text" %>
		<%= f.text_field :volunteers %></div>

		<div class="other"><%= f.label :raised_funds, "Raised funds", class: "text" %>
		<%= f.text_field :raised_funds %></div>

		<%= f.submit "Submit", class: "btn-large btn-success sgnBtn" %>
	<% end %>
</div>

<%# render "form" %>

app/views/updates/show.html.erb
<%= link_to "Change privacy", change_privacy_company_update_path(), method: "post" %>
<%= @update.privacy %>
<h3>Updates</h3>
<p><%= @update.update_SEI %></p>

<h3>Challenges</h3>
<p><%= @update.challenge %></p>

<h3>Support required</h3>
<p><%= @update.support_req %></p>

<h3>People impacted</h3>
<p><%= @update.impact %></p>

<h3>Number of employees</h3>
<p><%= @update.employed %></p>

<h3>Number of volunteers</h3>
<p><%= @update.volunteers %></p>

<h3>Raised funds</h3>
<p><%= @update.raised_funds %></p>